### ISSUE TITLE
More points in pub.dev

### ISSUE THREAD

**Issue by guyluz11** [Slins-23/flutter-fft#10]
Let's get more points in pub.dev by fixing the analysis

![Screenshot_20230909_225807_Firefox](https://github.com/Slins-23/flutter-fft/assets/9304740/76b5a5fe-ebfa-4fa4-b89a-c1ecfd14a263)

**Comment by Slins-23** [comment]
Thank you for the heads up, but this was a learning project and my goal was not for it to be a proper polished and optimized plugin to be used by many people, it was mostly for me to learn and use.

Which is why I have to humbly decline this commit, as that would go against the purpose I made this.
