### ISSUE TITLE
Recorder never starts

### ISSUE THREAD

**Issue by doodatales** [Slins-23/flutter-fft#2]
When calling method _async() (based off of example code in repo), nothing happens.  Recording doesn't start, no streams opened, data isn't transferred.  Tried moving _async() out of the init state and into a button but this didn't affect anything.  Any advice?

### Plugin version: 
1.0.1

## flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.48.2)
[✓] Connected device (1 available)

### Tested environment (Emulator? Real Device?)
Emulator: Pixel 2 API 29 Android 10.0

**Comment by apemangr** [comment]
Works only in physical devices for me. It didn't work on emulators.

**Comment by Slins-23** [comment]
> Works only in physical devices for me. It didn't work on emulators.

Don't know if that's the reason why, but check if you have enabled the microphone in the emulator settings.

**Comment by Slins-23** [comment]
> When calling method _async() (based off of example code in repo), nothing happens. Recording doesn't start, no streams opened, data isn't transferred. Tried moving _async() out of the init state and into a button but this didn't affect anything. Any advice?
> 
> ### Plugin version:
> 1.0.1
> 
> ## flutter doctor
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.6 19G73, locale en-US)
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
> [✓] Xcode - develop for iOS and macOS (Xcode 11.6)
> [✓] Android Studio (version 3.6)
> [✓] VS Code (version 1.48.2)
> [✓] Connected device (1 available)
> 
> ### Tested environment (Emulator? Real Device?)
> Emulator: Pixel 2 API 29 Android 10.0

Sorry, I really can't do much without access to your code, as it works fine for me.
Try updating to the newer version if possible, maybe that's fixed.
