### ISSUE TITLE
help: there are exceptions

### ISSUE THREAD

**Issue by jijkbird** [Slins-23/flutter-fft#6]
I've successfully converted to a piano tuner

But sometimes there are exceptions

I'm using flitter 1.22

D/FlutterFftPlugin(17488): KOKOKOKKOK, Excep: java.lang.IndexOutOfBoundsException: Index: 96, Size: 96
D/FlutterFftPlugin(17488): Exception: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(17488): FATAL EXCEPTION: main
E/AndroidRuntime(17488): Process: com.sankoumu.piano, PID: 17488
E/AndroidRuntime(17488): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(17488): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(17488): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:243)
E/AndroidRuntime(17488): 	at com.slins.flutterfft.PitchModel.updateFrequencyAndNote(PitchModel.java:90)
E/AndroidRuntime(17488): 	at com.slins.flutterfft.FlutterFftPlugin.lambda$startRecorder$2$FlutterFftPlugin(FlutterFftPlugin.java:132)
E/AndroidRuntime(17488): 	at com.slins.flutterfft.-$$Lambda$FlutterFftPlugin$pF_eBEYizOoYVMOf-xcXt-dNttY.run(Unknown Source:4)
E/AndroidRuntime(17488): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(17488): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(17488): 	at android.os.Looper.loop(Looper.java:233)
E/AndroidRuntime(17488): 	at android.app.ActivityThread.main(ActivityThread.java:8010)
E/AndroidRuntime(17488): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(17488): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
E/AndroidRuntime(17488): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

**Comment by Slins-23** [comment]
Are you still experiencing this exception with the newest update? I know exactly where this error occurs, and thought I had fixed it.

**Comment by jijkbird** [comment]
I'm using version 1.0.1

**Comment by jijkbird** [comment]
Because I use flitter 1.22

**Comment by Slins-23** [comment]
> Because I use flitter 1.22

You can fix this error in the 1.0.1 version by commenting out the "result.error" lines in some of the Java files and replacing them with "return". You can see the updated version's Java files and compare them to find the changes.

**Comment by Slins-23** [comment]
There's also another exception that can occur, which you can fix by going into PitchModel.java and modifying the assigned value of the variable "currentIdx" from 0 to -1, and move the line "currentIdx++;" from above the "if" statement to inside it.
