### ISSUE TITLE
Can I adjust the volume of a specific frequency band using this library?

### ISSUE THREAD

**Issue by jaejin0me** [Slins-23/flutter-fft#9]
I am trying to create an app/website related to audio processing. As said in the title, is it possible to adjust the volume of a specific frequency?

**Comment by Slins-23** [comment]
With the methods provided by this library, no. Although you may be able to do so through the TarsosDSP Java library, which this Flutter library uses.

**Comment by jaejin0me** [comment]
Okay, Thank you for answer.
